--- #YAML:1.0
name: Hardware-Simulator-MIX
version: 0.03
author:
  - Chaoji Li <lichaoji@ict.ac.cn>
abstract: Knuth's famous virtual machine
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
